<?php
    $form = $this->form;
    $form->prepare();
?>

<h1 class="h3 mb-3 font-weight-normal text-center">Inscription</h1>
<?= $this->form()->openTag($form); ?>


<div class="form-row row">  
    <div class="form-group col-md-4 col-centered">
        <?= $this->formLabel($form->get('firstname')); ?>
        <?= $this->formElement($form->get('firstname')); ?>
        <?= $this->formElementErrors($form->get('firstname')); ?>
    </div>
</div>  
<div class="form-row row">  
    <div class="form-group col-md-4 col-centered">
        <?= $this->formLabel($form->get('lastname')); ?>
        <?= $this->formElement($form->get('lastname')); ?>
        <?= $this->formElementErrors($form->get('lastname')); ?>
    </div>
</div>  
<div class="form-row row">  
    <div class="form-group col-md-4 col-centered">
        <?= $this->formLabel($form->get('email')); ?>
        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>
    </div>
</div>  
<div class="form-row row">  
    <div class="form-group col-md-4 col-centered">
        <?= $this->formLabel($form->get('address')); ?>
        <?= $this->formElement($form->get('address')); ?>
        <?= $this->formElementErrors($form->get('address')); ?>
    </div>
</div>  
<div class="form-row row">  
    <div class="form-group col-md-4 col-centered">
        <?= $this->formLabel($form->get('city')); ?>
        <?= $this->formElement($form->get('city')); ?>
        <?= $this->formElementErrors($form->get('city')); ?>
    </div>
</div>  
<div class="form-row row">  
    <div class="form-group col-md-4 col-centered">
        <?= $this->formLabel($form->get('country')); ?>
        <?= $this->formElement($form->get('country')); ?>
        <?= $this->formElementErrors($form->get('country')); ?>
    </div>
</div>  
<div class="form-row row">  
    <div class="form-group col-md-4 col-centered">
        <?= $this->formLabel($form->get('username')); ?>
        <?= $this->formElement($form->get('username')); ?>
        <?= $this->formElementErrors($form->get('username')); ?> 
    </div>
</div>                  
<div class="form-row row">  
    <div class="form-group col-md-4 col-centered">
        <?= $this->formLabel($form->get('password')); ?>
        <?= $this->formElement($form->get('password')); ?>
        <?= $this->formElementErrors($form->get('password')); ?>
    </div>
</div>   
<div class="form-row row">  
    <div class="form-group col-md-4 col-centered">
        <?= $this->formLabel($form->get('passwordConfirm')); ?>
        <?= $this->formElement($form->get('passwordConfirm')); ?>
        <?= $this->formElementErrors($form->get('passwordConfirm')); ?>
    </div>
</div>                 
<div class="form-row row">  
    <div class="form-group col-md-3 col-centered">                        
        <?= $this->formElement($form->get('submit')); ?>
    </div>
</div>   

<?= $this->form()->closeTag(); ?>