<?php
    $form = $this->form;
    $form->prepare();
?>

<h1 class="h3 mb-3 font-weight-normal text-center">Ouvrir une session</h1>
<?= $this->form()->openTag($form); ?>

<div class="form-row row">  
    <div class="form-group col-md-4 col-centered">
        <?= $this->formLabel($form->get('username')); ?>
        <?= $this->formElement($form->get('username')); ?>
        <?= $this->formElementErrors($form->get('username')); ?> 
    </div>
</div>                  

<div class="form-row row">  
    <div class="form-group col-md-4 col-centered">
        <?= $this->formLabel($form->get('password')); ?>
        <?= $this->formElement($form->get('password')); ?>
        <?= $this->formElementErrors($form->get('password')); ?>
    </div>
</div>                  

<div class="form-row row">  
    <div class="form-group col-md-3 col-centered">                        
        <?= $this->formElement($form->get('submitButton')); ?>
    </div>
</div>   

<?= $this->form()->closeTag(); ?>