<main>
<?php

$form->prepare();
$form = $this->form;

$form->get('productName')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Name'
    ]);

$form->get('productPrice')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Price'
    ]);

$form->get('productDesc')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Description'
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Save');
?>

<h1>Entrez les informations du produit <?= $this->escapeHtml($product->productId); ?></h1>

<table class="datatable">
<tbody>
<?= $this->form()->openTag($form); ?>
        
<div class="form-row row">  
    <div class="form-group col-md-4 col-centered">
        <?= $this->formLabel($form->get('productName')); ?>
        <?= $this->formElement($form->get('productName')); ?>
        <?= $this->formElementErrors($form->get('productName')); ?> 
    </div>
</div>                  

<div class="form-row row">  
    <div class="form-group col-md-4 col-centered">
        <?= $this->formLabel($form->get('productPrice')); ?>
        <?= $this->formElement($form->get('productPrice')); ?>
        <?= $this->formElementErrors($form->get('productPrice')); ?>
    </div>
</div>       

<div class="form-row row">  
    <div class="form-group col-md-4 col-centered">
        <?= $this->formLabel($form->get('productDesc')); ?>
        <?= $this->formElement($form->get('productDesc')); ?>
        <?= $this->formElementErrors($form->get('productDesc')); ?>
    </div>
</div>     

<div class="form-row row">  
    <div class="form-group col-md-4 col-centered">
        <?= $this->formLabel($form->get('imageURL')); ?>
        <?= $this->formElement($form->get('imageURL')); ?>
        <!-- ?= $this->formFile($form->get('imageURL')); ?> -->
        <?= $this->formElementErrors($form->get('imageURL')); ?>
    </div>
</div>                

<div class="form-row row">  
    <div class="form-group col-md-3 col-centered">                        
        <?= $this->formElement($form->get('submit')); ?>
    </div>
</div>   

</main>