<main role=main>
 <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Catalogue en ligne</h1>
	  <p> Bienvenue a l'application de catalogue en ligne. Celle-ci vous permet de magasiner vos articles pr&eacute;f&eacute;r&eacute;s en ligne
        et de les ajouter a votre panier.</p>
          <p><a class="btn btn-lg btn-primary" href="<?= $this->url('catalogue')?>" role="button">Voir les articles</a></p>
        </div>
      </section>

      <div class="container marketing">
        <!-- Three columns of text below the carousel -->
        <div class="row">

	  <div class="col-lg-4">
            <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
	    <h2>Contexte</h2>
	    <p>Ce catalogue a &eacute;t&eacute; r&eacute;alis&eacute; dans le cadre du cours 8INF345-Technologies
	      Web Avanc&eacute;es.</p>
          </div><!-- /.col-lg-4 -->

          <div class="col-lg-4">
            <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
            <h2>Fait avec Angular 5</h2>
	    <p>Ce site contient les technologies HTML, CSS, javascript et typescript.
	      Il est enti&egrave;rement fait &agrave; la main, sans utilisation de framework.</p>
          </div><!-- /.col-lg-4 -->

	  <div class="col-lg-4">
            <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
	    <h2>Une &eacute;quipe de feu</h2>
	    <p>L'&eacute;quipe de projet est constitu&eacute;e de d&eacute;veloppeurs web professionnels. Plus sp&eacute;cifiquement,
	      Pierre-Marc Laforest, Alexandre Girard-Gagnon et Micha&euml;l Lizotte-Gagnon.</p>
          </div><!-- /.col-lg-4 -->

        </div><!-- /.row -->
      </div><!-- /.container -->

      <div id="last-section">
      </div>

    </main>      